export const Z_INDEX = {
  BACKGROUND: 0,
  PCB_TRACES: 5,
  CHIP_MODULES: 10,
  CHIP_MODULES_HOVER: 15,
  OVERLAYS: 20,
  TOOLTIPS: 30,
  POPUPS: 40,
  MODALS: 50,
  MODAL_BACKDROP: 45,
  HEADER: 100,
} as const;
